### ISSUE TITLE
api /login router fails to POST

### ISSUE THREAD

**Issue by g1-1-1** [salad-server/lettuce-web#4]
on top of having CORS issues (bypassed using an extension, but idk how to fix this one either -- putting a nginx `add-header` and/or adding both domains to `config.yaml`'s CORS options do not work), you cannot log in due to the login router not accepting any valid requests correctly.
![chrome_K3s2LGoMl3](https://user-images.githubusercontent.com/24374615/189474898-85976f59-5697-4ada-b2e1-6691044db356.png)
demonstration of cors issue

![image](https://user-images.githubusercontent.com/24374615/189474887-9006777e-bc06-49ce-9159-597f02056faf.png)
![image](https://user-images.githubusercontent.com/24374615/189474892-bc1a7a3d-66b5-4226-b447-b59cc48e9172.png)
failed login attempts

**Comment by Cyan903** [comment]
Sorry for the late reply. Try replacing your CORS in `config.yaml` with this:
```yaml
CORS:
  - https://web.halcyon.moe
  - https://halcyon.moe
```

The config I posted in #3 doesn't use a subdomain so that might be messing with cors. This is what I had in my config when I ran under the `web.` subdomain though.

**Comment by g1-1-1** [comment]
changing my nginx configuration to use the frontend on the main domain does not work all the same, and the configuration you gave does not work either

**Comment by Cyan903** [comment]
You shouldn't have anything related to cors in your nginx config. You just need to add your frontend (web.halcyon.moe) and the root domain to `CORS` in `config.yaml`.

Do you mind sharing your nginx? It's weird that only post requests seem to give cors errors.

**Comment by g1-1-1** [comment]
> Do you mind sharing your nginx?

[here](https://pastebin.com/raw/NCyxUBM3)

**Comment by Cyan903** [comment]
Alright I took a look through your nginx and I see some possible issues. `lettuce` and `lettuce-api` are configured properly, but your `bancho.py` is a bit strange.

On line 44, you have the standard `bancho.py` configuration:
![image](https://user-images.githubusercontent.com/88910588/189645944-79a828be-d24c-470c-a37c-fadc19f298a1.png)

Which looks fine, but you also have another `bancho.py` server directly under it (line 75):
![image](https://user-images.githubusercontent.com/88910588/189646115-682ca238-c2b8-4e00-bdd6-7327e14e4c4b.png)

I'm assuming the second image is the config for the frontend you're running on [https://halcyon.moe/home](https://halcyon.moe/home). I don't know much about the frontend you're running, but I don't understand why you would need two `proxy_pass` for `bancho.py`. Also on line 75, there is a rule for `web`. There is a chance that this is one of the reasons you're facing CORS issues, as you have `add_header "Access-Control-Allow-Origin" "*";` in that block.

I suggest removing lines 74-82. See if that has any affect on your frontend (the one you're running now, not lettuce).

---

Another thing I noticed is that the uptime for the server has not changed since you made the first issue.
![image](https://user-images.githubusercontent.com/88910588/189647722-3439f114-81b3-4325-8af8-2f60cb8b17da.png)

There is no live reload feature, everytime you edit a config you must restart. 

- For `config.json`, you need to run `npm run build`.
- For `api/config.yaml` you just need to restart the `mini-api` process.


The reason I bring this up is because from what I can see, it doesn't look like the config has been applied. Here's what a GET and POST request look like on my server:

![image](https://user-images.githubusercontent.com/88910588/189649419-8222f335-6d53-4391-960b-ff9c0cf06415.png)
![image](https://user-images.githubusercontent.com/88910588/189649505-3d3d143d-86d1-4f2f-af33-be791fb6b68b.png)

On those requests, there is an `access-control-allow-origin` header pointing to my frontend. That's why I don't have any cors issues, because the API allows requests sent from my frontend.

On your server, you don't have any cors headers.

![image](https://user-images.githubusercontent.com/88910588/189649804-32f84c53-78fc-4ffc-a4be-f1883b9c8282.png)

Which is why every request is failing.

---

Update `config.yaml` with the code I posted [here](https://github.com/salad-server/lettuce-web/issues/4#issuecomment-1242717721). Then restart the `mini-api` process. If that doesn't fix your cors issues, remove lines 74-82 from your nginx config. I don't think those lines are required to run the frontend you're currently running, as most of those subdomains don't even exist.

Sorry for the wall of text, I should probably create some sort of install script or image.

**Comment by 0i8** [comment]
for the second image you reference: everything under the gulag comment are directories that gulag uses for redirects or as is (for example, [/ss/](https://osu.halcyon.moe/ss/SXvs3no1.jpeg)

will update when i can update everything else

**Comment by g1-1-1** [comment]
for the second image of the nginx configuration, i am pretty sure those are directories that are used by gulag as redirects or in general, just used -- for example, [/ss/](https://osu.halcyon.moe/ss/SXvs3no1.jpeg) is used for screenshots, like on bancho.

removing the lines from the nginx configuration as requested (although i did not think to be the problem), ultimately did not work. 

`config.yaml` includes the [frontend](https://new.halcyon.moe) (i changed urls) and the root domain already.

i have, numerous times, rebuilt and relaunched the program as you mention -- no idea why it shows that as the counter for uptime.

if this were ultimately an issue with CORS, and it blocking access to the api -- [then why do the leaderboards](https://new.halcyon.moe/leaderboard?m=vn%21std), and [user profiles](https://new.halcyon.moe/leaderboard?m=vn%21std) work? if CORS were the issue, shouldn't it block _any_ api requests, regardless of what it is?

**Comment by Cyan903** [comment]
Here's the thing, I can't recreate this issue. I've rerun through the install a few times on vms and cts. I even setup a linode Ubuntu server using the provided nginx config (only changing `ssl` and `server_name`) and had no CORS issues.

>  if CORS were the issue, shouldn't it block any api requests, regardless of what it is?

You're right, it's even weirder that OPTION requests seem to return the proper headers, yet for some reason POST will return nothing related to CORS.

![image](https://user-images.githubusercontent.com/88910588/189997480-54c648dd-7da9-46a5-9afb-42640e545d60.png)

---

If the API refuses to set the cors header, you can set it manually with this:

```
# lettuce-web api
server {
	listen 80;
	listen 443 ssl;

	server_name wapi.example.com;

	ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
	ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";

	location / {
		proxy_set_header "Access-Control-Allow-Origin" "*";
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_pass http://127.0.0.1:8081;
	}
}
```

Then replace the cors config in `config.yaml` with `*`:

![image](https://user-images.githubusercontent.com/88910588/189998293-c1443c53-a3fa-40c5-9184-ad23fbaf5fbb.png)

```sh
$ sudo nginx -s reload
$ ./mini-api
```

---

But before you do that, I have one last suggestion. I'm honestly just guessing at this point because I have no way of recreating the issue but I think you're using the wrong node/go version.

Your frontend is generating a bunch of errors. These errors are unrelated to the api, you can see them by simply going to the home page.

![image](https://user-images.githubusercontent.com/88910588/189999230-d497faf9-ea35-4e37-b938-021f88f4f1dd.png)

This is probably because the frontend was built with the wrong node version. Here's what my version shows:

```sh
$ node -v
v16.17.0
```

If you're using the same version, you can ignore this. But to install the proper node version, you'll need [nvm](https://github.com/nvm-sh/nvm#install--update-script).

Install nvm with:
```sh
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
$ source ~/.bashrc
```

Then install the proper version:
```sh
$ nvm install --lts
$ nvm use --lts --default
$ cd /path/to/lettuce-web
$ npm run build
```

---

You should do the same with go as well. This *might* be the cause of the CORS issues. Here's what mine shows:

```sh
$ go version
go version go1.18.1 linux/amd64
```

If your version shows 1.18.1 or 1.18 you're good and you can skip this. You need [gvm](https://github.com/moovweb/gvm#installing) to install the proper go version.

```sh
# go is required for gvm to install (for some reason)
$ sudo apt install golang-go
$ bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
$ source ~/.gvm/scripts/gvm

$ gvm install go1.18.1
$ gvm use go1.18.1 --default
$ cd /path/to/lettuce-web/api
$ make build
```

**Comment by Cyan903** [comment]
Here's my discord if you want `hwk929#3391`. I'm fine with using Github, but discord might be a bit faster for things like this.

**Comment by Cyan903** [comment]
Ended up being an issue with cloudflare. Resolved in dms.
